services:
  template-db:
    image: postgres:17
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
